name: abctechapp
description: AbcTechApp - Solution Sprint 3

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.5.1
  http: ^0.13.4
  lazy_load_scrollview: ^1.3.0
  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.16
  build_runner: ^2.1.5

flutter:
  uses-material-design: true